# Setup
title:               alelouis
tagline:             'Science Fiction'
description:         'Nouvelles de Science Fiction.'
url:                 https://alelouis-sf.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alexis LOUIS
  url:
  email:             alelouis.sf@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
